### ISSUE TITLE
Feature: observe all events

### ISSUE THREAD

**Issue by jtmcgrath** [fanduel-oss/refract#70]
## Description

Could be a worthwhile addition: add the ability to observe _any_ event passed to `pushEvent` by calling `component.event()` (similar to `component.observe()` without a propName). Came up when talking some stuff through with @mylesj.

### Before

```js
const aperture = () => component =>
	merge(
		component.event('event1').map(value => ['event1', value]),
		component.event('event2').map(value => ['event2', value]),
		component.event('event3').map(value => ['event3', value]),
	).map(toAnalytics)
```
### After
```js
const aperture = () => component =>
	component.event().map(toAnalytics)
```

### Possible Extension

The example raises the question of what data structure should be returned so that both the eventName and the value are exposed. Maybe providing the ability to pass a mapping function would be a good solution?

```js
const aperture = () => component =>
	component.event((event, value) => [event, value]).map(toAnalytics)

const aperture = () => component =>
	component.event((event, value) => ({ event, value })).map(toAnalytics)
```

**Comment by troch** [comment]
Not sure, I think it adds a bit of complexity to the API (due to the need) to pass a function to map event name and event to a value. I can't really think of a benefit of observing all events rather than specific ones: a common event namespace can be shared instead.

I think it would be good to support `Symbol` though, with `event(string | Symbol)`.
